name       : libev
version    : '4.27'
release    : 4
source     :
    - http://dist.schmorp.de/libev/libev-4.27.tar.gz : 2d5526fc8da4f072dd5c73e18fbb1666f5ef8ed78b73bba12e195cfdd810344e
license    : BSD-2-Clause
summary    : libev is a high-performance event loop/event model with lots of features.
component  : system.utils
description: |
    Libev is modelled (very loosely) after libevent and the Event perl module, but is faster, scales better and is more correct, and also more featureful. And also smaller.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # conflict with libevent
    rm $installdir/usr/include/event.h
