name       : libev
version    : 4.22
release    : 1
source     :
    - http://dist.schmorp.de/libev/libev-4.22.tar.gz : 736079e8ac543c74d59af73f9c52737b3bfec9601f020bf25a87a4f4d0f01bd6
license    : BSD-2-Clause
summary    : libev is a high-performance event loop/event model with lots of features.
component  : system.utils
description: |
    Libev is modelled (very loosely) after libevent and the Event perl module, but is faster, scales better and is more correct, and also more featureful. And also smaller.
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
