name       : libev
version    : 4.24
release    : 2
source     :
    - http://dist.schmorp.de/libev/libev-4.24.tar.gz : 973593d3479abdf657674a55afe5f78624b0e440614e2b8cb3a07f16d4d7f821
license    : BSD-2-Clause
summary    : libev is a high-performance event loop/event model with lots of features.
component  : system.utils
description: |
    Libev is modelled (very loosely) after libevent and the Event perl module, but is faster, scales better and is more correct, and also more featureful. And also smaller.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # conflict with libevent
    rm $installdir/usr/include/event.h
