name       : libev
version    : '4.25'
release    : 3
source     :
    - http://dist.schmorp.de/libev/libev-4.25.tar.gz : 78757e1c27778d2f3795251d9fe09715d51ce0422416da4abb34af3929c02589
license    : BSD-2-Clause
summary    : libev is a high-performance event loop/event model with lots of features.
component  : system.utils
description: |
    Libev is modelled (very loosely) after libevent and the Event perl module, but is faster, scales better and is more correct, and also more featureful. And also smaller.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # conflict with libevent
    rm $installdir/usr/include/event.h
